#!/usr/bin/env node
//
// scripts/devSignIos.mjs
//
// Strips the paid-only `aps-environment` entitlement from
// `ios/Sukoon/Sukoon.entitlements` so the app can be installed on a real
// iPhone using Xcode's Free Apple Developer Program signing (Personal Team).
//
// Why: the entitlement is generated by the expo-notifications plugin during
// prebuild even though Sukoon only schedules LOCAL notifications and has no
// remote push pipeline. Removing it lets Xcode auto-sign with a free Apple ID.
//
// Notes:
//   - The Widget extension's App Groups entitlement is kept — App Groups DO
//     work with free Personal Team signing when used to share data with your
//     own app's extensions (which is exactly our case).
//   - Builds signed this way expire after 7 days; re-install weekly.
//   - This script is REVERSIBLE: run with `--restore` to put the entitlement
//     back when you switch to production signing.
//
// Usage:
//   node scripts/devSignIos.mjs                  # strip (default)
//   node scripts/devSignIos.mjs --restore        # restore from backup
//   node scripts/devSignIos.mjs --status         # show current state
//
// Convention: a backup with the production entitlements is kept at
// `ios/Sukoon/Sukoon.entitlements.prod-backup` and is ignored by git.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');
const ENTITLEMENTS_PATH = path.join(REPO_ROOT, 'ios', 'Sukoon', 'Sukoon.entitlements');
const BACKUP_PATH = `${ENTITLEMENTS_PATH}.prod-backup`;

const APS_KEY_BLOCK_REGEX = /\s*<key>\s*aps-environment\s*<\/key>\s*<string>[^<]*<\/string>/i;

function readEntitlements() {
  if (!fs.existsSync(ENTITLEMENTS_PATH)) {
    console.error(`✗ Entitlements file not found at ${ENTITLEMENTS_PATH}`);
    console.error('  Run `npx expo prebuild` first to generate the native iOS project.');
    process.exit(1);
  }
  return fs.readFileSync(ENTITLEMENTS_PATH, 'utf8');
}

function hasApsEnvironment(content) {
  return APS_KEY_BLOCK_REGEX.test(content);
}

function reportStatus() {
  const content = readEntitlements();
  const hasIt = hasApsEnvironment(content);
  const backupExists = fs.existsSync(BACKUP_PATH);
  console.log('Sukoon iOS entitlement state:');
  console.log(`  File:            ${path.relative(REPO_ROOT, ENTITLEMENTS_PATH)}`);
  console.log(`  aps-environment: ${hasIt ? 'PRESENT (production)' : 'STRIPPED (dev-sign ready)'}`);
  console.log(`  Backup:          ${backupExists ? path.relative(REPO_ROOT, BACKUP_PATH) : '(none)'}`);
  if (hasIt) {
    console.log('\n  → To dev-sign: node scripts/devSignIos.mjs');
  } else {
    console.log('\n  → To restore: node scripts/devSignIos.mjs --restore');
  }
}

function strip() {
  const content = readEntitlements();
  if (!hasApsEnvironment(content)) {
    console.log('✓ aps-environment is already stripped. No changes made.');
    if (fs.existsSync(BACKUP_PATH)) {
      console.log(`  (Backup exists at ${path.relative(REPO_ROOT, BACKUP_PATH)})`);
    }
    return;
  }

  if (!fs.existsSync(BACKUP_PATH)) {
    fs.writeFileSync(BACKUP_PATH, content, 'utf8');
    console.log(`✓ Backed up production entitlements → ${path.relative(REPO_ROOT, BACKUP_PATH)}`);
  } else {
    console.log(`  (Existing backup at ${path.relative(REPO_ROOT, BACKUP_PATH)} preserved)`);
  }

  const stripped = content.replace(APS_KEY_BLOCK_REGEX, '');
  fs.writeFileSync(ENTITLEMENTS_PATH, stripped, 'utf8');
  console.log(`✓ Stripped aps-environment from ${path.relative(REPO_ROOT, ENTITLEMENTS_PATH)}`);
  console.log('');
  console.log('Next steps:');
  console.log('  1. In Xcode → Sukoon target → Signing & Capabilities,');
  console.log('     REMOVE the "Push Notifications" capability if it appears.');
  console.log('     (It may auto-reappear; just remove it each time.)');
  console.log('  2. Set Team to your Personal Team (free Apple ID).');
  console.log('  3. Connect iPhone, select it as build target, Cmd+R.');
  console.log('  4. On iPhone: Settings → General → VPN & Device Management →');
  console.log('     trust the developer profile (your Apple ID).');
  console.log('');
  console.log('Reminder: the install expires after 7 days. Re-run this + Cmd+R weekly.');
}

function restore() {
  if (!fs.existsSync(BACKUP_PATH)) {
    console.error(`✗ No backup found at ${path.relative(REPO_ROOT, BACKUP_PATH)}.`);
    console.error('  Nothing to restore — either run `npx expo prebuild` to regenerate,');
    console.error('  or manually re-add the aps-environment key.');
    process.exit(1);
  }
  const backup = fs.readFileSync(BACKUP_PATH, 'utf8');
  fs.writeFileSync(ENTITLEMENTS_PATH, backup, 'utf8');
  console.log(`✓ Restored production entitlements from ${path.relative(REPO_ROOT, BACKUP_PATH)}`);
  console.log('  (The backup file is kept in place — safe to leave.)');
}

const arg = process.argv[2];

if (arg === '--status' || arg === '-s') {
  reportStatus();
} else if (arg === '--restore' || arg === '-r') {
  restore();
} else if (arg === undefined || arg === '--strip') {
  strip();
} else if (arg === '--help' || arg === '-h') {
  console.log('Usage:');
  console.log('  node scripts/devSignIos.mjs              # strip aps-environment (default)');
  console.log('  node scripts/devSignIos.mjs --restore    # restore from backup');
  console.log('  node scripts/devSignIos.mjs --status     # show current state');
} else {
  console.error(`Unknown flag: ${arg}`);
  console.error('Run with --help to see usage.');
  process.exit(1);
}
